Shift install scripts; new bin/mux script

diff --git a/bin/git-clean-merged b/bin/git-clean-merged
--- a/bin/git-clean-merged
+++ b/bin/git-clean-merged
@@ -1,4 +1,41 @@
 #!/bin/sh
-# Usage: git-clean-merged
-# Deleted local branches that have been merged
-git branch --merged | grep -v "\*" | xargs -n 1 git branch -d
+#
+# Delete all branches that have been merged to master && push deletes to remote origin
+# from: https://github.com/SnapInteractive/git-tools
+# 
+# Usage: git clean-merged
+
+CHECK_ORIGIN=$(git remote -v | grep '^origin.\+(push)$')
+if [ -z "$CHECK_ORIGIN" ]; then
+	echo "You need to be in a git repo with a pushable \"origin\" remote!"
+	exit 1
+fi
+
+if [ "$1" = "-i" ]; then
+	INTERACTIVE="yes"
+else
+	INTERACTIVE=""
+fi
+
+for BRANCH in $(git branch --merged master | grep -v '\<master\>\|^\*'); do
+	if [ -n "$INTERACTIVE" ]; then
+		read -p "$(basename $0): remove branch '$BRANCH'? (y)" RESPONSE
+		if [  "$RESPONSE" != 'y' ] && [ "$RESPONSE" != '' ]; then
+			continue
+		fi
+	fi
+	ST=$(git branch -d "$BRANCH" 2>&1)
+	if [ $? -eq 0 ]; then
+		echo "Pruned \"$BRANCH\"; removing from origin...\c"
+		RST=$(git push origin ":$BRANCH" 2>&1)
+		if [ $? -eq 0 ]; then
+			echo " Removed."
+		else
+			echo
+			echo "Branch \"$BRANCH\" not removed from origin: $RST"
+		fi
+	else
+		ST=$(echo "$ST" | head -n 1 | sed 's/error: //')
+		echo "Branch \"$BRANCH\" not removed: $ST"
+	fi
+done
